controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\IndexController::index

login:
    path: /login
    controller: App\Controller\LoginController::login